name: Build

on:
  push:
    branches:
      - feature/github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.PULL_TOKEN }}
      - name: Fetch full history for Shijima submodules
        env:
          PULL_TOKEN: ${{ secrets.PULL_TOKEN }}
        run: |
          pushd libshijima
          git remote set-url origin "https://${PULL_TOKEN}@github.com/pixelomer/libshijima.git"
          git fetch --unshallow origin main
          git remote set-url origin "git@github.com:pixelomer/libshijima"
          echo "libshijima: $(git rev-list HEAD --count) commits"
          popd
      - name: Build Docker image
        run: |
          pushd dev-docker
          docker build -t shijima-qt-dev .
          popd
      - name: Build Windows 64-bit debug build
        run: |
          docker run -e CONFIG=debug --rm -v "$(pwd)":/work -it shijima-qt-dev bash -c \
            'mingw64-make clean && mingw64-make -j$(nproc)'
      - name: Archive Windows 64-bit debug build
        uses: actions/upload-artifact@v4
        with:
          name: debug-windows-x86_64
          path: publish/Windows/debug
      - name: Build Windows 32-bit debug build
        run: |
          docker run -e CONFIG=debug --rm -v "$(pwd)":/work -it shijima-qt-dev bash -c \
            'mingw32-make clean && mingw32-make -j$(nproc)'
      - name: Archive Windows 32-bit debug build
        uses: actions/upload-artifact@v4
        with:
          name: debug-windows-i386
          path: publish/Windows/debug
      - name: Build Linux x86_64 debug build
        run: |
          docker run -e CONFIG=debug --rm -v "$(pwd)":/work -it shijima-qt-dev bash -c \
            'make clean && make -j$(nproc)'
      - name: Archive Linux x86_64 debug build
        uses: actions/upload-artifact@v4
        with:
          name: debug-linux-x86_64
          path: publish/Linux/debug
